# Gestor de fondos de pantalla
# Aplicación de fondo para preservar el diseño general

# Necesario para el control por comandos o scripts
ipc = on
# Desactivar branding para mantener el minimalismo
splash = false

# Uso de ruta absoluta referenciando el repositorio
preload = /home/pedrojreyes/MyArch/assets/wallpapers/solid_dark.png
wallpaper = , /home/pedrojreyes/MyArch/assets/wallpapers/solid_dark.png
