# Inicio automático
# Servicios y demonios requeridos en segundo plano

# Asegurar integración de variables para portales y apps de Wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Entorno de escritorio esencial
exec-once = waybar
exec-once = swaync
exec-once = hyprpaper

# Manejo de energía y bloqueo de pantalla
exec-once = hypridle

# Persistencia del portapapeles
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = nwg-dock-hyprland -d -i 48 -a center -nolauncher
