# Reglas de ventanas
# Control específico del comportamiento de ciertas aplicaciones

# Flotar utilidades para evitar que rompan el tiling
windowrulev2 = float, class:^(pavucontrol|nm-connection-editor|blueman-manager|file-roller|imv|mpv)$

# Diálogos y ajustes deben flotar por naturaleza
windowrulev2 = float, title:(Open File|Save As|Preferences|Settings)

# Configuración de Picture-in-Picture (PiP) para fijarlo siempre visible
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = size 480 270, title:^(Picture-in-Picture)$
windowrulev2 = move 100%-490 40, title:^(Picture-in-Picture)$

# Evitar que la pantalla se apague al ver multimedia
windowrulev2 = idleinhibit fullscreen, class:^(firefox|mpv|chromium)$

# Prevenir que aplicaciones monopolicen el redimensionamiento
windowrulev2 = suppressevent maximize, class:.*

# Diferenciar visualmente el gestor de archivos
windowrulev2 = opacity 0.95 0.95, class:^(nemo)$
