# Reglas de ventanas
# Control específico del comportamiento de ciertas aplicaciones

# Flotar utilidades para evitar que rompan el tiling
windowrule = float on, match:class ^(pavucontrol|nm-connection-editor|blueman-manager|file-roller|imv|mpv)$

# Diálogos y ajustes deben flotar por naturaleza
windowrule = float on, match:title (Open File|Save As|Preferences|Settings)

# Configuración de Picture-in-Picture (PiP) para fijarlo siempre visible
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = size 480 270, match:title ^(Picture-in-Picture)$
windowrule = move 100%-490 40, match:title ^(Picture-in-Picture)$

# Evitar que la pantalla se apague al ver multimedia
windowrule = idle_inhibit fullscreen, match:class ^(firefox|mpv|chromium)$

# Prevenir que aplicaciones monopolicen el redimensionamiento
windowrule = suppress_event maximize, match:class .*

# Diferenciar visualmente el gestor de archivos
windowrule = opacity 0.95 0.95, match:class ^(nemo)$
