monitor.bluez.rules = [
  {
    matches = [
      { node.name = "~bluez_output.*" }
    ]
    actions = {
      update-props = {
        priority.driver = 1500
        priority.session = 1500
      }
    }
  }
]
